name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_SECRET: ${{ secrets.GH_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      # Headless Chromium
      - name: Install Chromium and dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser

      - name: Run Maven build image command
        run: mvn spring-boot:build-image -P prod